version: '3'
services:

  api:
    build: .
    image: middleware/rest:latest
    hostname: api
    environment:
      - PORT=3000
      - DATABASE_HOST=mariadb
      - DATABASE_PORT=3306
      - DATABASE_NAME=middleware
      - DATABASE_USER=root
      - DATABASE_PASS=root
    ports:
      - 3000:3000
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.3
    hostname: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=middleware
    ports:
      - 3306:3306
      - 5567:5567
